[language-server.clasangd]
command="clasangd"
args =["--verbose","1","--name","/tmp/clasangd"]
[[language]]
name="c"
language-servers=["clasangd","clangd"]
[[language]]
name="cpp"
language-servers=["clasangd","clangd"]
